This code takes the data from Licitaciones and retrieves all information about the bids.

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import seaborn as sns
from pandasgui import show
import socket

## Licitaciones files

### Find the date of the 'Licitaciones' for each FA code.

In [ ]:
base_path = os.path.join('..','raw_data','Licitaciones')

years = range(2022, 2025) 
months = range(1, 13) #13
relevant_periods = []
for year in years: 
    for month in months: 
        path = os.path.join(base_path, f'{year}', f'lic_{year}-{month}.csv')
        df = pd.read_csv(path, sep = ';', encoding='latin1')

        df17 = df[df['CodigoExterno'] == '2239-4-LR17']
        df21 = df[df['CodigoExterno'] == '2239-5-LR21']
        df23 = df[df['CodigoExterno'] == '2239-8-LR23']

        rows_2017 = len(df17) 
        rows_2021 = len(df21)
        rows_2023 = len(df23) 

        if rows_2017 + rows_2021 + rows_2023 > 0:
            print(f'For {year}-{month} the number of observations are:', rows_2017, rows_2021, rows_2023)
            relevant_periods.append((year, month))

C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (63,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,73,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,59,63,64,65,73,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,59,63,64,73,87,94,97,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (63,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')

For 2023-6 the number of observations are: 0 0 95

C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (63,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,65,87,94,97,99,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (27,52,63,64,73,87,94,97,99,100,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (14,15,27,44,54,56,59,63,64,73,74,87,94,97,99,100,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')
C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\4238409507.py:7: DtypeWarning: Columns (87,97,99,100,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep = ';', encoding='latin1')

In [25]:
print(relevant_periods)

[(2023, 6)]

From the previous code we know that the auction for  '2239-4-LR17' is in 2017-5, for '2239-5-LR21' is in 2021-4 and for '2239-8-LR23' is in ------

In [32]:
path17 = os.path.join(base_path, '2017', 'lic_2017-5.csv')
path21 = os.path.join(base_path, '2021', 'lic_2021-4.csv')
path23 = os.path.join(base_path, '2023', 'lic_2023-6.csv')


df  = pd.read_csv(path17, sep = ';', encoding='latin1')
df17 =  df[df['CodigoExterno'] == '2239-4-LR17']

df  = pd.read_csv(path21, sep = ';', encoding='latin1')
df21 = df[df['CodigoExterno'] == '2239-5-LR21']

df  = pd.read_csv(path23, sep = ';', encoding='latin1')
df23 = df[df['CodigoExterno'] == '2239-8-LR23']

C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\1741685402.py:6: DtypeWarning:

Columns (27,52,63,64,87,97,101,102) have mixed types. Specify dtype option on import or set low_memory=False.

C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\1741685402.py:9: DtypeWarning:

Columns (27,52,63,64,87,97,101) have mixed types. Specify dtype option on import or set low_memory=False.

C:\Users\lucas\AppData\Local\Temp\ipykernel_20852\1741685402.py:12: DtypeWarning:

Columns (27,52,63,64,87,94,97,101) have mixed types. Specify dtype option on import or set low_memory=False.

In [33]:
print("\nOne per line:")
for col in df17.columns:
    print(col)

One per line:
Codigo
Link
CodigoExterno
Nombre
Descripcion
Tipo de Adquisicion
CodigoEstado
Estado
CodigoOrganismo
NombreOrganismo
sector
RutUnidad
CodigoUnidad
NombreUnidad
DireccionUnidad
ComunaUnidad
RegionUnidad
Informada
CodigoTipo
Tipo
TipoConvocatoria
CodigoMoneda
Moneda Adquisicion
Etapas
EstadoEtapas
TomaRazon
EstadoPublicidadOfertas
JustificacionPublicidad
EstadoCS
Contrato
Obras
CantidadReclamos
FechaCreacion
FechaCierre
FechaInicio
FechaFinal
FechaPubRespuestas
FechaActoAperturaTecnica
FechaActoAperturaEconomica
FechaPublicacion
FechaAdjudicacion
FechaEstimadaAdjudicacion
FechaSoporteFisico
FechaTiempoEvaluacion
UnidadTiempoEvaluacion
FechaEstimadaFirma
FechasUsuario
FechaVisitaTerreno
DireccionVisita
FechaEntregaAntecedentes
DireccionEntrega
Estimacion
FuenteFinanciamiento
VisibilidadMonto
MontoEstimado
Tiempo
UnidadTiempo
Modalidad
TipoPago
ProhibicionContratacion
SubContratacion
UnidadTiempoDuracionContrato
TiempoDuracionContrato
TipoDuracionContrato
JustificacionMontoEstimado
ObservacionContrato
ExtensionPlazo
EsBaseTipo
UnidadTiempoContratoLicitacion
ValorTiempoRenovacion
PeriodoTiempoRenovacion
EsRenovable
TipoAprobacion
NumeroAprobacion
FechaAprobacion
NumeroOferentes
Correlativo
CodigoEstadoLicitacion
Codigoitem
CodigoProductoONU
Rubro1
Rubro2
Rubro3
Nombre producto genrico
Nombre linea Adquisicion
Descripcion linea Adquisicion
UnidadMedida
Cantidad
CodigoProveedor
CodigoSucursalProveedor
RutProveedor
NombreProveedor
RazonSocialProveedor
DescripcionProveedor
Monto Estimado Adjudicado
Nombre de la Oferta
Estado Oferta
Cantidad Ofertada
Moneda de la Oferta
MontoUnitarioOferta
Valor Total Ofertado
CantidadAdjudicada
MontoLineaAdjudica
FechaEnvioOferta
Oferta seleccionada

In [46]:
# If your dataframe is a Pandas DataFrame:
columns_to_keep = [
    'Link', 'CodigoExterno',
    'FechaInicio', 'FechaFinal',
    'FechaAdjudicacion', 'MontoEstimado',
    'TiempoDuracionContrato', 'NumeroOferentes',
    'Codigoitem', 'Nombre producto genrico',
    'UnidadMedida', 'Cantidad',
    'CodigoProveedor', 'CodigoSucursalProveedor',
    'RutProveedor', 'NombreProveedor',
    'Monto Estimado Adjudicado', 'Estado Oferta',
    'Cantidad Ofertada', 'Moneda de la Oferta',
    'Oferta seleccionada'
]

df17 = df17[columns_to_keep]
df21 = df21[columns_to_keep]
df23 = df23[columns_to_keep]

print(len(df17), len(df21), len(df23))


df_combined = pd.concat([df17, df21, df23], ignore_index=True)
print(df_combined.shape)

126 27 95
(248, 21)

In [47]:
show(df_combined)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

## Planillas files

In [72]:
base_path = os.path.join('..','raw_data','CM cars auction')
path_prices_21 = os.path.join(base_path, 'Planilla_General_Evaluación_-_ID_2239-4-LR17_(Publicación).xlsx')


df_aux1 = pd.read_excel(path_prices_21, sheet_name = 'Camionetas') 
df_aux2 = pd.read_excel(path_prices_21, sheet_name = 'SUV') 
# check that 
print( list(df_aux1.columns) == list(df_aux2.columns), " dfs have same columns")
print(df_aux1.columns) 
print(df_aux2.columns)

# concatenate the two dfs 
df_prices21 = pd.concat([df_aux1, df_aux2], axis=0)

### For 2017

### For 2021

In [55]:
path_prices_21 = os.path.join(base_path, 'Planilla_de_adjudicación_CM_Vehículos_ID_2239-5-LR21_V.F..xlsx')

df_aux1 = pd.read_excel(path_prices_21, sheet_name = 'Camionetas') 
df_aux2 = pd.read_excel(path_prices_21, sheet_name = 'SUV') 

# check that 
print( list(df_aux1.columns) == list(df_aux2.columns), " dfs have same columns")
print(df_aux1.columns) 
print(df_aux2.columns)

# concatenate the two dfs 
df_prices21 = pd.concat([df_aux1, df_aux2], axis=0)

,RUT,Nombre,Estado Anterior,Categoría,Macrozona,Gama,Opción,Precio,Cumple precio máximo,Marca,Modelo,Versión,Cumple carta Marca,Cumple requisitos técnicos Gama,Precio + Despacho,Precio Macrozona-Gama,Puntaje Precio
0,76.005.909-9,COMERCIAL MOTORES DE LOS ANDES,ADMISIBLE,Camionetas,Norte,Gama 2,Opción1,12278400.0,SI,Maxus,T60,4x2 DX,SI,SI,13052500,14044500,82.638755
1,76.005.909-9,COMERCIAL MOTORES DE LOS ANDES,ADMISIBLE,Camionetas,Norte,Gama 2,Opción2,13430400.0,SI,Maxus,T60,4X2 GL,SI,SI,14204500,14044500,82.638755
2,76.005.909-9,COMERCIAL MOTORES DE LOS ANDES,ADMISIBLE,Camionetas,Norte,Gama 2,Opción3,14102400.0,SI,Maxus,T60,4X4 DX,SI,SI,14876500,14044500,82.638755
3,76.005.909-9,COMERCIAL MOTORES DE LOS ANDES,ADMISIBLE,Camionetas,Centro,Gama 2,Opción1,12278400.0,SI,Maxus,T60,4X2 DX,SI,SI,12445400,13437400,86.549481
4,76.005.909-9,COMERCIAL MOTORES DE LOS ANDES,ADMISIBLE,Camionetas,Centro,Gama 2,Opción2,13430400.0,SI,Maxus,T60,4X2 GL,SI,SI,13597400,13437400,86.549481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,96.981.470-6,CONVERSIONES SAN JOSE,ADMISIBLE,Camionetas,Sur,Gama 4,Opción1,20015600.0,SI,Nissan,NAVARA,MC DC SE,SI,SI,20250600,20250600,70.440382
297,96.981.470-6,CONVERSIONES SAN JOSE,ADMISIBLE,Camionetas,Austral,Gama 2,Opción1,13182300.0,SI,Maxus,T60,DX 6MT 4X2,SI,SI,14182300,14861300,83.898448
298,96.981.470-6,CONVERSIONES SAN JOSE,ADMISIBLE,Camionetas,Austral,Gama 2,Opción2,14540300.0,SI,Maxus,T60,DX 6MT 4X4,SI,SI,15540300,14861300,83.898448
299,96.981.470-6,CONVERSIONES SAN JOSE,ADMISIBLE,Camionetas,Austral,Gama 3,Opción1,16195348.0,SI,Nissan,NAVARA,MC DC SE,SI,SI,17195348,17195348,78.187426
300,96.981.470-6,CONVERSIONES SAN JOSE,ADMISIBLE,Camionetas,Austral,Gama 4,Opción1,20015600.0,SI,Nissan,NAVARA,MC DC SE,SI,SI,21015600,21015600,70.236396

In [62]:
# check that 
print( list(df_aux1.columns) == list(df_aux2.columns), " dfs have same columns")
print(df_aux1.columns) 
print(df_aux2.columns)

# concatenate the two dfs 
df_prices21 = pd.concat([df_aux1, df_aux2], axis=0)

True  dfs have same columns
Index(['RUT', 'Nombre', 'Estado Anterior', 'Categoría', 'Macrozona', 'Gama',
       'Opción', 'Precio', 'Cumple precio máximo', 'Marca', 'Modelo',
       'Versión', 'Cumple carta Marca', 'Cumple requisitos técnicos Gama',
       'Precio + Despacho', 'Precio Macrozona-Gama', 'Puntaje Precio'],
      dtype='object')
Index(['RUT', 'Nombre', 'Estado Anterior', 'Categoría', 'Macrozona', 'Gama',
       'Opción', 'Precio', 'Cumple precio máximo', 'Marca', 'Modelo',
       'Versión', 'Cumple carta Marca', 'Cumple requisitos técnicos Gama',
       'Precio + Despacho', 'Precio Macrozona-Gama', 'Puntaje Precio'],
      dtype='object')

In [56]:
show(df_aux1)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [71]:
path_prices_23 = os.path.join(base_path, 'PROVEEDORES_-_Evaluación_CM_Vehículos_y_maquinarias.xlsx') 
df_aux3 = pd.read_excel(path_prices_23, sheet_name = 2, skiprows=2)

#df_aux3 = pd.read_excel(path_prices_21, sheet_name = 'Evaluación Adm - Tec')
df_aux3

,Unnamed: 0,Nombre,Tipo Producto,Modelo,Categoría,Medida,Región Romano,Región N°,RUT,Nombre Fantasia,...,Puntaje ponderado ST,Puntaje ponderado Despacho,Puntaje ponderado descuento,Puntaje Total,Total proveedores por ficha a rankear,Ranking a adjudicar 60%,Ranking,Estado Adjudicación inicial,Regla adjudicación Mínimo proveedores,Adjudicación final (regla mín 5 reg y 10 RM)
0,NaN,BUS PESADO DIESEL DESCUENTO REGIÓN I,BUS PESADO,DIESEL,Vehículos pesados y maquinarias,DESCUENTO REGIÓN I,REGIÓN I,1,76.005.909-9,Motores de los Andes S.A.,...,15,20.000000,60.0,100,15,9.0,1,Adjudica,5,Adjudica
1,NaN,BUS PESADO DIESEL DESCUENTO REGIÓN I,BUS PESADO,DIESEL,Vehículos pesados y maquinarias,DESCUENTO REGIÓN I,REGIÓN I,1,76.099.641-6,Covemin,...,15,20.000000,60.0,100,15,9.0,1,Adjudica,5,Adjudica
2,NaN,BUS PESADO DIESEL DESCUENTO REGIÓN I,BUS PESADO,DIESEL,Vehículos pesados y maquinarias,DESCUENTO REGIÓN I,REGIÓN I,1,76.758.790-2,HYUNDAI VEHICULOS COMERCIALES,...,15,20.000000,60.0,100,15,9.0,1,Adjudica,5,Adjudica
3,NaN,BUS PESADO DIESEL DESCUENTO REGIÓN I,BUS PESADO,DIESEL,Vehículos pesados y maquinarias,DESCUENTO REGIÓN I,REGIÓN I,1,76.821.750-5,TMG,...,15,11.347059,30.0,61.347059,15,9.0,12,No Adjudica,5,No Adjudica
4,NaN,BUS PESADO DIESEL DESCUENTO REGIÓN I,BUS PESADO,DIESEL,Vehículos pesados y maquinarias,DESCUENTO REGIÓN I,REGIÓN I,1,77.004.491-K,VIS SPA,...,15,20.000000,60.0,100,15,9.0,1,Adjudica,5,Adjudica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4377,NaN,TOLVA GASOLINA DESCUENTO REGIÓN III,TOLVA,GASOLINA,Vehículos pesados y maquinarias,DESCUENTO REGIÓN III,REGIÓN III,3,96.877.150-7,PENA SPOERER Y CIA S A,...,15,20.000000,60.0,100,3,1.8,1,Adjudica,5,Adjudica
4378,NaN,TOLVA GASOLINA DESCUENTO REGIÓN III,TOLVA,GASOLINA,Vehículos pesados y maquinarias,DESCUENTO REGIÓN III,REGIÓN III,3,96.981.470-6,CONVERSIONES SAN JOSE - Vehículos Especiales,...,15,0.000000,36.0,56,3,1.8,2,No Adjudica,5,Adjudica
4379,NaN,TOLVA GASOLINA DESCUENTO REGIÓN IV,TOLVA,GASOLINA,Vehículos pesados y maquinarias,DESCUENTO REGIÓN IV,REGIÓN IV,4,76.821.750-5,TMG,...,15,20.000000,60.0,100,2,1.2,1,Adjudica,5,Adjudica
4380,NaN,TOLVA GASOLINA DESCUENTO REGIÓN IV,TOLVA,GASOLINA,Vehículos pesados y maquinarias,DESCUENTO REGIÓN IV,REGIÓN IV,4,96.877.150-7,PENA SPOERER Y CIA S A,...,15,20.000000,100.0,Inadmisible,2,1.2,Inadmisible,No Adjudica,5,No Adjudica
4381,NaN,TOLVA GASOLINA DESCUENTO REGIÓN IV,TOLVA,GASOLINA,Vehículos pesados y maquinarias,DESCUENTO REGIÓN IV,REGIÓN IV,4,96.981.470-6,CONVERSIONES SAN JOSE - Vehículos Especiales,...,15,20.000000,60.0,100,2,1.2,1,Adjudica,5,Adjudica

In [69]:
show(df_aux3)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI